services:
  db:
    image: postgres:16-alpine
    container_name: next-landing-page-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payloadcms
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payloadcms"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 🟢 Esto fuerza a Next.js a compilar sabiendo que su raíz es /biblioteca
        NEXT_PUBLIC_SERVER_URL: https://www.atlanticomedio.es/biblioteca
        PAYLOAD_PUBLIC_SERVER_URL: https://www.atlanticomedio.es/biblioteca
    container_name: next-landing-page-frontend-1
    ports:
      - "8085:3000"
    volumes:
      - media_data:/app/media
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WATCHPACK_POLLING=true
      - PAYLOAD_SECRET=9fc076e667cb808e40733d2b
      - DATABASE_URI=postgres://postgres:1234@db:5432/payloadcms
      # Se mantienen en ejecución por si Payload las consulta dinámicamente en el servidor
      - NEXT_PUBLIC_SERVER_URL=https://www.atlanticomedio.es/biblioteca
      - PAYLOAD_PUBLIC_SERVER_URL=https://www.atlanticomedio.es/biblioteca
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}

volumes:
  postgres_data:
  media_data: