services:
  db:
    image: postgres:16-alpine
    container_name: landing-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1234}
      POSTGRES_DB: payloadcms
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      target: deps # Solo instalamos dependencias, no hacemos build
    container_name: landing-frontend-dev
    ports:
      - "8085:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app 
      - /app/node_modules # Protege los binarios de Linux
      - /app/.next # Evita conflictos de caché con Windows
      - media_data:/app/media
    environment:
      WATCHPACK_POLLING: "true" # Obligatorio para Hot Reload en Windows
      CHOKIDAR_USEPOLLING: "true" # Payload y otras herramientas usan Chokidar internamente
      NEXT_WDS_POLLING: "true"
      NODE_ENV: development
    command: npm run dev # Usamos el modo dev de Next.js
    depends_on:
      - db

volumes:
  postgres_data_dev:
  media_data: