services:
  bibliotecadb:
    image: postgres:16-alpine
    container_name: biblioteca-db
    env_file:
      - .env.local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: biblioteca-frontend
    env_file:
      .env.local
    ports:
      - "8085:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - media_data:/app/media
    depends_on:
      bibliotecadb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
    - WATCHPACK_POLLING=true

volumes:
  postgres_data:
  media_data: