FROM node:24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package*.json tsconfig.json ./

RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
# CMD ["sh", "-c", "npx payload migrate:create && npx payload migrate && npm run dev"]